### ISSUE TITLE
What is the output?

### ISSUE THREAD

**Issue by antithing** [JingJie-Huang/IMU-Calibration#1]
Hi, and thank you for making this code available! 

I am looking to calibrate the covariance for both the accelerometer and gyroscope, is this the result of this code?

Thanks again

**Comment by JingJie-Huang** [comment]
> Hi, and thank you for making this code available!
> 
> I am looking to calibrate the covariance for both the accelerometer and gyroscope, is this the result of this code?
> 
> Thanks again

Dear antithing,

Thank you for the reply, actually I followed the methodology in the video link as below.
Links:
https://www.youtube.com/watch?v=-1tmYPE7MAQ&t=47s
The output of my code are accelerometer and gyroscope parameters, they are bias, scale and non-orthgoanl factor.
Not including covariance part.
Thanks!

**Comment by antithing** [comment]
Thanks! I appreciate you getting back to me.
